#CELL 1
# FictionalCart Microsoft Excel Capstone Project

## Notebook 01 – Customer_Master_Dirty_Generation

### Objective

This notebook generates a realistic dirty version of the Customer Master dataset.

The original Customer_Master.csv remains unchanged and acts as the Master Dataset.

Python is used only to inject planned business data quality issues.

The dirty dataset will later be cleaned completely in Microsoft Excel as part of the Excel Data Analyst portfolio project.

The final cleaned dataset should exactly match the original master dataset.

In [1]:
#CELL 2 - IMPORT LIBRARIES

import pandas as pd
import numpy as np
import random

In [2]:
#CELL 3 - SET RANDOM SEED

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

In [3]:
#CELL4 - READ THE MASTER DATASET

customer_master = pd.read_csv("../01_Master_Datasets/Customer_Master.csv")

In [4]:
#Validation
print(customer_master.head())
print(customer_master.shape)

  Customer_ID   Customer_Name  Gender  Age           City           State  \
0       C0001  Rohan Kulkarni    Male   26         Ranchi       Jharkhand
1       C0002     Vivaan Jain    Male   26  Visakhapatnam  Andhra Pradesh
2       C0003     Deepika Das  Female   38        Lucknow   Uttar Pradesh
3       C0004    Aadhya Kumar  Female   29          Surat         Gujarat
4       C0005   Shreya Shetty  Female   38      Hyderabad       Telangana

  Customer_Segment   Join_Date
0          Regular  2025-08-30
1           Budget  2023-01-19
2          Regular  2023-08-23
3           Budget  2024-12-09
4           Budget  2025-07-01
(750, 8)

In [5]:
#CELL 5 - CREATE A WORKING COPY

customer_dirty = customer_master.copy(deep=True)

In [6]:
customer_dirty.head()

,Customer_ID,Customer_Name,Gender,Age,City,State,Customer_Segment,Join_Date
0,C0001,Rohan Kulkarni,Male,26,Ranchi,Jharkhand,Regular,2025-08-30
1,C0002,Vivaan Jain,Male,26,Visakhapatnam,Andhra Pradesh,Budget,2023-01-19
2,C0003,Deepika Das,Female,38,Lucknow,Uttar Pradesh,Regular,2023-08-23
3,C0004,Aadhya Kumar,Female,29,Surat,Gujarat,Budget,2024-12-09
4,C0005,Shreya Shetty,Female,38,Hyderabad,Telangana,Budget,2025-07-01

In [7]:
customer_master.equals(customer_dirty)

True

In [8]:
#CELL 6 - DEFINE THE ERROR INJECTION PLAN

ERROR_PLAN = {
    "leading_trailing_spaces": 30,
    "double_spaces": 20,
    "mixed_case": 20,
    "all_caps": 15,
    "all_lowercase": 15,
    "hidden_characters": 10,
    "blank_city": 15,
    "state_abbreviations": 20,
    "join_date_as_text": 25,
    "duplicate_records": 10
}

In [9]:
ERROR_PLAN

{'leading_trailing_spaces': 30,
 'double_spaces': 20,
 'mixed_case': 20,
 'all_caps': 15,
 'all_lowercase': 15,
 'hidden_characters': 10,
 'blank_city': 15,
 'state_abbreviations': 20,
 'join_date_as_text': 25,
 'duplicate_records': 10}

In [10]:
sum(ERROR_PLAN.values())

180

In [11]:
#CELL 7 - SELECT ROWS FOR LEADING & TRAILING SPACES

leading_space_rows = random.sample(
    customer_dirty.index.tolist(),
    ERROR_PLAN["leading_trailing_spaces"]
)

In [12]:
#Validation 1
len(leading_space_rows)

30

In [13]:
#Validation 2
leading_space_rows

[654,
 114,
 25,
 281,
 250,
 228,
 142,
 104,
 692,
 558,
 89,
 604,
 432,
 32,
 30,
 95,
 223,
 238,
 517,
 616,
 27,
 574,
 203,
 733,
 665,
 718,
 429,
 225,
 459,
 603]

In [14]:
#Validation 3
len(set(leading_space_rows))

30

In [15]:
#Validation 4
customer_dirty.loc[leading_space_rows].head()

,Customer_ID,Customer_Name,Gender,Age,City,State,Customer_Segment,Join_Date
654,C0655,Akash Kapoor,Male,34,Hyderabad,Telangana,Regular,2023-03-13
114,C0115,Aryan Singh,Male,49,Chennai,Tamil Nadu,Budget,2023-07-21
25,C0026,Deepika Das,Female,38,Chennai,Tamil Nadu,Budget,2025-11-18
281,C0282,Ananya Pandey,Female,25,Hyderabad,Telangana,Premium,2024-06-25
250,C0251,Aadhya Nair,Female,34,Chennai,Tamil Nadu,Premium,2024-03-07

In [16]:
#CELL 8 - INJECT LEADING & TRAILING SPACES

for row in leading_space_rows:

    current_name = customer_dirty.loc[row, "Customer_Name"]

    space_type = random.choice([
        "leading",
        "trailing",
        "both"
    ])

    if space_type == "leading":
        customer_dirty.loc[row, "Customer_Name"] = " " + current_name

    elif space_type == "trailing":
        customer_dirty.loc[row, "Customer_Name"] = current_name + " "

    else:
        customer_dirty.loc[row, "Customer_Name"] = " " + current_name + " "

In [17]:
#VALIDATION 1
customer_dirty.loc[
    leading_space_rows,
    ["Customer_ID", "Customer_Name"]
].head(10)

    Customer_ID     Customer_Name
654       C0655     Akash Kapoor
114       C0115       Aryan Singh
25        C0026       Deepika Das
281       C0282    Ananya Pandey
250       C0251      Aadhya Nair
228       C0229      Priya Menon
142       C0143     Swathi Verma
104       C0105   Vihaan Kulkarni
692       C0693     Shreya Kapoor
558       C0559     Shreya Patel

In [18]:
#VALIDATION 2
comparison = pd.DataFrame({
    "Master": customer_master.loc[
        leading_space_rows,
        "Customer_Name"
    ],
    "Dirty": customer_dirty.loc[
        leading_space_rows,
        "Customer_Name"
    ]
})

comparison = pd.DataFrame({
    "Master": customer_master.loc[leading_space_rows, "Customer_Name"].apply(repr),
    "Dirty": customer_dirty.loc[leading_space_rows, "Customer_Name"].apply(repr)
})

comparison

                Master               Dirty
654     'Akash Kapoor'     'Akash Kapoor '
114      'Aryan Singh'      ' Aryan Singh'
25       'Deepika Das'      ' Deepika Das'
281    'Ananya Pandey'   ' Ananya Pandey '
250      'Aadhya Nair'      'Aadhya Nair '
228      'Priya Menon'      'Priya Menon '
142     'Swathi Verma'     'Swathi Verma '
104  'Vihaan Kulkarni'  ' Vihaan Kulkarni'
692    'Shreya Kapoor'    ' Shreya Kapoor'
558     'Shreya Patel'     'Shreya Patel '
89     'Vivaan Kapoor'    ' Vivaan Kapoor'
604       'Diya Joshi'       ' Diya Joshi'
432      'Kavya Gowda'      'Kavya Gowda '
32      'Kiran Mishra'     ' Kiran Mishra'
30      'Aditya Gowda'     'Aditya Gowda '
95    'Krishna Kapoor'   'Krishna Kapoor '
223     'Aditya Menon'    ' Aditya Menon '
238       'Aryan Bose'       'Aryan Bose '
517   'Krishna Pillai'   ' Krishna Pillai'
616      'Meera Gowda'     ' Meera Gowda '
27     'Ananya Shetty'    'Ananya Shetty '
574        'Pooja Rao'       ' Pooja Rao '
203     'Aryan Pandey'     ' Aryan Pandey'
733    'Aadhya Pillai'    'Aadhya Pillai '
665     'Ritika Joshi'     ' Ritika Joshi'
718    'Krishna Joshi'   ' Krishna Joshi '
429  'Deepika Agarwal'  'Deepika Agarwal '
225    'Swathi Shetty'   ' Swathi Shetty '
459     'Akash Pillai'    ' Akash Pillai '
603      'Aryan Verma'      'Aryan Verma '

In [19]:
#CELL 9 - INITIALIZE USED ROWS TRACKER

used_rows = set(leading_space_rows)

In [20]:
#VALLIDATION 1
len(used_rows)

30

In [21]:
#VALIDATION 2
used_rows

{25,
 27,
 30,
 32,
 89,
 95,
 104,
 114,
 142,
 203,
 223,
 225,
 228,
 238,
 250,
 281,
 429,
 432,
 459,
 517,
 558,
 574,
 603,
 604,
 616,
 654,
 665,
 692,
 718,
 733}

In [22]:
#CELL 10 - SELECT ROWS FOR DOUBLE SPACES

available_rows = list(set(customer_dirty.index) - used_rows)

double_space_rows = random.sample(
    available_rows,
    ERROR_PLAN["double_spaces"]
)

In [23]:
#CELL 11 - INJECT DOUBLE SPACES INTO Customer_Name

for row in double_space_rows:

    original_name = customer_master.loc[row, "Customer_Name"]

    customer_dirty.loc[row, "Customer_Name"] = original_name.replace(
        " ",
        "  ",
        1
    )

In [24]:
#VALIDATION 1
comparison = pd.DataFrame({
    "Master": customer_master.loc[
        double_space_rows,
        "Customer_Name"
    ].apply(repr),

    "Dirty": customer_dirty.loc[
        double_space_rows,
        "Customer_Name"
    ].apply(repr)
})

comparison

                  Master                 Dirty
615         'Aryan Bhat'         'Aryan  Bhat'
206        'Aarav Menon'        'Aarav  Menon'
75        'Sanjay Sinha'       'Sanjay  Sinha'
50          'Nisha Jain'         'Nisha  Jain'
705      'Sanjay Shetty'      'Sanjay  Shetty'
247        'Diya Shetty'        'Diya  Shetty'
312       'Aadhya Gupta'       'Aadhya  Gupta'
85           'Kavya Das'          'Kavya  Das'
253         'Nisha Iyer'         'Nisha  Iyer'
110      'Vivaan Mishra'      'Vivaan  Mishra'
405      'Krishna Sinha'      'Krishna  Sinha'
300      'Vihaan Sharma'      'Vihaan  Sharma'
483        'Anika Singh'        'Anika  Singh'
677         'Rohan Bose'         'Rohan  Bose'
389       'Rohan Pandey'       'Rohan  Pandey'
175  'Ananya Chatterjee'  'Ananya  Chatterjee'
395       'Vivaan Gowda'       'Vivaan  Gowda'
379         'Kavya Iyer'         'Kavya  Iyer'
226       'Shreya Kumar'       'Shreya  Kumar'
714        'Pooja Menon'        'Pooja  Menon'

In [25]:
#VALIDATION 2
(
    customer_master["Customer_Name"]
    !=
    customer_dirty["Customer_Name"]
).sum()

50

In [26]:
#VALIDATION 3
len(set(leading_space_rows) & set(double_space_rows))

0

In [27]:
used_rows.update(double_space_rows)

In [28]:
double_space_rows[0]

615

In [29]:
repr(customer_dirty.loc[double_space_rows[0], "Customer_Name"])

"'Aryan  Bhat'"

In [30]:
repr(customer_master.loc[double_space_rows[0], "Customer_Name"])

"'Aryan Bhat'"

In [31]:
customer_dirty.loc[
    double_space_rows[0],
    "Customer_Name"
].count(" ")

2

In [32]:
#CELL 12 - SELECT ROWS FOR MIXED CAPITALIZATION

available_rows = list(set(customer_dirty.index) - used_rows)

mixed_case_rows = random.sample(
    available_rows,
    ERROR_PLAN["mixed_case"]
)

In [33]:
len(mixed_case_rows)

20

In [34]:
len(set(mixed_case_rows))

20

In [35]:
len(set(mixed_case_rows) & used_rows)

0

In [36]:
customer_dirty.loc[
    mixed_case_rows,
    ["Customer_ID", "Customer_Name"]
].head()

    Customer_ID Customer_Name
298       C0299   Rahul Verma
749       C0750   Sanjay Bose
710       C0711   Ananya Jain
79        C0080  Meera Pillai
667       C0668   Rohan Patel

In [37]:
#CELL 13 - INJECT MIXED CAPITALIZATION INTO CUSTOMER_NAME

def random_mixed_case(text):
    """
    Convert alphabetic characters to random upper/lower case.
    Guarantees that the output differs from the input.
    """

    while True:

        mixed = "".join(
            random.choice([char.upper(), char.lower()])
            if char.isalpha()
            else char
            for char in text
        )

        if mixed != text:
            return mixed

In [38]:
#CELL 13 - INJECT MIXED CAPITALIZATION INRO Customer_Name

def random_mixed_case(text):
    """
    Convert alphabetic characters to random upper/lower case.
    Non-alphabetic characters (such as spaces) remain unchanged.
    """

    return "".join(
        random.choice([char.upper(), char.lower()]) if char.isalpha() else char
        for char in text
    )


for row in mixed_case_rows:

    original_name = customer_master.loc[row, "Customer_Name"]

    customer_dirty.loc[row, "Customer_Name"] = random_mixed_case(original_name)

In [39]:
comparison = pd.DataFrame({
    "Master": customer_master.loc[
        mixed_case_rows,
        "Customer_Name"
    ].apply(repr),

    "Dirty": customer_dirty.loc[
        mixed_case_rows,
        "Customer_Name"
    ].apply(repr)
})

comparison

                 Master               Dirty
298       'Rahul Verma'       'rahUL vErma'
749       'Sanjay Bose'       'SaNJay boSE'
710       'Ananya Jain'       'aNANYA jAin'
79       'Meera Pillai'      'meERa pIllAi'
667       'Rohan Patel'       'RoHAn PAtEL'
696  'Kiran Chatterjee'  'kiRAn cHATTErJEE'
189        'Sneha Iyer'        'sNehA Iyer'
584       'Nikhil Iyer'       'niKHIL iYER'
274     'Ritika Sharma'     'RITIKA sHArmA'
181       'Ananya Bhat'       'AnAnyA BHat'
508          'Sai Iyer'          'sai IYEr'
419       'Aarav Gupta'       'aARAV gUpTa'
302       'Swathi Bose'       'sWAtHI BOSE'
701     'Sanjay Sharma'     'sanJaY ShArma'
610      'Nikhil Singh'      'nikHIl SINgH'
245       'Meera Naidu'       'MeERA NAIDu'
359         'Aryan Roy'         'ARYAn roY'
62       'Sanjay Kumar'      'sAnjAy kuMAr'
258        'Diya Verma'        'DIYa VeRMa'
36       'Sanjay Naidu'      'sAnjAy NAiDU'

In [40]:
(
    customer_master["Customer_Name"]
    !=
    customer_dirty["Customer_Name"]
).sum()

70

In [41]:
len(set(mixed_case_rows) & used_rows)

0

In [42]:
used_rows.update(mixed_case_rows)

In [43]:
len(used_rows)

70

In [44]:
#CELL 14 - SELECT ROWS FOR ALL CAPS

available_rows = list(set(customer_dirty.index) - used_rows)

all_caps_rows = random.sample(
    available_rows,
    ERROR_PLAN["all_caps"]
)

In [45]:
len(all_caps_rows)

15

In [46]:
len(set(all_caps_rows))

15

In [47]:
len(set(all_caps_rows) & used_rows)

0

In [48]:
customer_dirty.loc[
    all_caps_rows,
    ["Customer_ID", "Customer_Name"]
].head()

    Customer_ID   Customer_Name
623       C0624   Neha Malhotra
176       C0177     Aadhya Jain
315       C0316  Aadhya Agarwal
325       C0326         Sai Roy
680       C0681    Ritika Menon

In [49]:
#CELL 15 - INJECT ALL CAPS INTO Customer_Name

for row in all_caps_rows:

    original_name = customer_master.loc[row, "Customer_Name"]

    customer_dirty.loc[row, "Customer_Name"] = original_name.upper()

In [50]:
comparison = pd.DataFrame({
    "Master": customer_master.loc[
        all_caps_rows,
        "Customer_Name"
    ].apply(repr),

    "Dirty": customer_dirty.loc[
        all_caps_rows,
        "Customer_Name"
    ].apply(repr)
})

comparison

               Master             Dirty
623   'Neha Malhotra'   'NEHA MALHOTRA'
176     'Aadhya Jain'     'AADHYA JAIN'
315  'Aadhya Agarwal'  'AADHYA AGARWAL'
325         'Sai Roy'         'SAI ROY'
680    'Ritika Menon'    'RITIKA MENON'
241     'Vihaan Jain'     'VIHAAN JAIN'
391    'Pooja Pandey'    'POOJA PANDEY'
233      'Meera Jain'      'MEERA JAIN'
716   'Arjun Agarwal'   'ARJUN AGARWAL'
306   'Rohan Agarwal'   'ROHAN AGARWAL'
567     'Pooja Kumar'     'POOJA KUMAR'
549    'Aryan Sharma'    'ARYAN SHARMA'
290       'Sai Menon'       'SAI MENON'
58   'Deepika Kapoor'  'DEEPIKA KAPOOR'
107      'Nikhil Rao'      'NIKHIL RAO'

In [51]:
(
    customer_master["Customer_Name"]
    !=
    customer_dirty["Customer_Name"]
).sum()

85

In [52]:
len(set(all_caps_rows) & used_rows)

0

In [53]:
used_rows.update(all_caps_rows)

In [54]:
len(used_rows)

85

In [55]:
#CELL 16 - SELECT ROWS FOR ALL LOWERCASE

available_rows = list(set(customer_dirty.index) - used_rows)

lowercase_rows = random.sample(
    available_rows,
    ERROR_PLAN["all_lowercase"]
)

In [56]:
len(lowercase_rows)

15

In [57]:
len(set(lowercase_rows))

15

In [58]:
len(set(lowercase_rows) & used_rows)

0

In [59]:
customer_dirty.loc[
    lowercase_rows,
    ["Customer_ID", "Customer_Name"]
].head()

    Customer_ID     Customer_Name
732       C0733        Meera Iyer
490       C0491  Krishna Kulkarni
329       C0330        Diya Menon
51        C0052        Arjun Bose
3         C0004      Aadhya Kumar

In [60]:
#CELL 17 - INJECT ALL LOWERCASE INTO Customer_Name

for row in lowercase_rows:

    original_name = customer_master.loc[row, "Customer_Name"]

    customer_dirty.loc[row, "Customer_Name"] = original_name.lower()

In [61]:
comparison = pd.DataFrame({
    "Master": customer_master.loc[
        lowercase_rows,
        "Customer_Name"
    ].apply(repr),

    "Dirty": customer_dirty.loc[
        lowercase_rows,
        "Customer_Name"
    ].apply(repr)
})

comparison

                 Master               Dirty
732        'Meera Iyer'        'meera iyer'
490  'Krishna Kulkarni'  'krishna kulkarni'
329        'Diya Menon'        'diya menon'
51         'Arjun Bose'        'arjun bose'
3        'Aadhya Kumar'      'aadhya kumar'
390         'Kavya Rao'         'kavya rao'
151    'Sneha Kulkarni'    'sneha kulkarni'
736      'Ananya Singh'      'ananya singh'
311           'Sai Rao'           'sai rao'
186      'Aryan Kapoor'      'aryan kapoor'
510       'Kavya Verma'       'kavya verma'
634          'Diya Das'          'diya das'
494    'Anika Malhotra'    'anika malhotra'
644        'Meera Nair'        'meera nair'
9       'Sneha Agarwal'     'sneha agarwal'

In [62]:
(
    customer_master["Customer_Name"]
    !=
    customer_dirty["Customer_Name"]
).sum()

100

In [63]:
len(set(lowercase_rows) & used_rows)

0

In [64]:
used_rows.update(lowercase_rows)

In [65]:
len(used_rows)

100

In [66]:
#CELL 18 - SELECT ROWS FOR HIDDEN CHARACTERS

available_rows = list(set(customer_dirty.index) - used_rows)

hidden_character_rows = random.sample(
    available_rows,
    ERROR_PLAN["hidden_characters"]
)

In [67]:
len(hidden_character_rows)

10

In [68]:
len(set(hidden_character_rows))

10

In [69]:
len(set(hidden_character_rows) & used_rows)

0

In [70]:
customer_dirty.loc[
    hidden_character_rows,
    ["Customer_ID", "Customer_Name"]
].head()

    Customer_ID  Customer_Name
134       C0135  Nikhil Sharma
92        C0093   Aadhya Verma
174       C0175   Rahul Mishra
640       C0641  Krishna Verma
43        C0044  Sanjay Shetty

In [71]:
#CELL 19 - INJECT HIDDEN CHARACTERS INTO Customer_Name

for row in hidden_character_rows:

    original_name = customer_master.loc[row, "Customer_Name"]

    customer_dirty.loc[row, "Customer_Name"] = (
        original_name.replace(" ", "\t", 1)
    )

In [72]:
comparison = pd.DataFrame({
    "Master": customer_master.loc[
        hidden_character_rows,
        "Customer_Name"
    ].apply(repr),

    "Dirty": customer_dirty.loc[
        hidden_character_rows,
        "Customer_Name"
    ].apply(repr)
})

comparison

               Master              Dirty
134   'Nikhil Sharma'   'Nikhil\tSharma'
92     'Aadhya Verma'    'Aadhya\tVerma'
174    'Rahul Mishra'    'Rahul\tMishra'
640   'Krishna Verma'   'Krishna\tVerma'
43    'Sanjay Shetty'   'Sanjay\tShetty'
441  'Kiran Kulkarni'  'Kiran\tKulkarni'
684    'Aryan Pandey'    'Aryan\tPandey'
648     'Sneha Sinha'     'Sneha\tSinha'
173      'Neha Reddy'      'Neha\tReddy'
507   'Sanjay Pandey'   'Sanjay\tPandey'

In [73]:
(
    customer_master["Customer_Name"]
    !=
    customer_dirty["Customer_Name"]
).sum()

110

In [74]:
len(set(hidden_character_rows) & used_rows)

0

In [75]:
used_rows.update(hidden_character_rows)

In [76]:
len(used_rows)

110

In [77]:
#CELL 20 - SELECT ROWS FOR BLANK CITY

available_rows = list(set(customer_dirty.index) - used_rows)

blank_city_rows = random.sample(
    available_rows,
    ERROR_PLAN["blank_city"]
)

In [78]:
len(blank_city_rows)

15

In [79]:
len(set(blank_city_rows))

15

In [80]:
len(set(blank_city_rows) & used_rows)

0

In [81]:
customer_dirty.loc[
    blank_city_rows,
    ["Customer_ID", "City"]
].head()

    Customer_ID       City
155       C0156  Bengaluru
52        C0053    Kolkata
374       C0375      Surat
442       C0443    Lucknow
48        C0049  Bengaluru

In [82]:
#CELL 21 - INJECT BLANK CITY

for row in blank_city_rows:

    customer_dirty.loc[row, "City"] = pd.NA

In [83]:
customer_dirty.loc[
    blank_city_rows,
    ["Customer_ID", "City"]
]

    Customer_ID  City
155       C0156  <NA>
52        C0053  <NA>
374       C0375  <NA>
442       C0443  <NA>
48        C0049  <NA>
434       C0435  <NA>
261       C0262  <NA>
308       C0309  <NA>
127       C0128  <NA>
428       C0429  <NA>
668       C0669  <NA>
487       C0488  <NA>
744       C0745  <NA>
190       C0191  <NA>
291       C0292  <NA>

In [84]:
customer_dirty["City"].isna().sum()

15

In [85]:
(
    customer_master["City"]
    !=
    customer_dirty["City"]
).sum()

15

In [86]:
used_rows.update(blank_city_rows)

In [87]:
len(used_rows)

125

In [88]:
#CELL 22 - SELECT ROWS FOR STATE ABBREVATIONS

available_rows = list(set(customer_dirty.index) - used_rows)

state_abbreviation_rows = random.sample(
    available_rows,
    ERROR_PLAN["state_abbreviations"]
)

In [89]:
len(state_abbreviation_rows)

20

In [90]:
len(set(state_abbreviation_rows))

20

In [91]:
len(set(state_abbreviation_rows) & used_rows)

0

In [92]:
customer_dirty.loc[
    state_abbreviation_rows,
    ["Customer_ID", "State"]
].head()

    Customer_ID          State
204       C0205      Karnataka
220       C0221         Kerala
511       C0512  Uttar Pradesh
29        C0030      Telangana
222       C0223    West Bengal

In [93]:
#CELL 23 - INJECT STATE ABBREVIATIONS

STATE_ABBREVIATIONS = {
    "Andhra Pradesh": "AP",
    "Assam": "AS",
    "Bihar": "BR",
    "Chandigarh": "CH",
    "Delhi": "DL",
    "Gujarat": "GJ",
    "Jharkhand": "JH",
    "Karnataka": "KA",
    "Kerala": "KL",
    "Maharashtra": "MH",
    "Odisha": "OD",
    "Rajasthan": "RJ",
    "Tamil Nadu": "TN",
    "Telangana": "TS",
    "Uttar Pradesh": "UP",
    "West Bengal": "WB"
}

# ============================================================
# Inject State Abbreviations
# ============================================================

for row in state_abbreviation_rows:

    original_state = customer_master.loc[row, "State"]

    customer_dirty.loc[row, "State"] = STATE_ABBREVIATIONS[original_state]

In [94]:
comparison = pd.DataFrame({
    "Master": customer_master.loc[
        state_abbreviation_rows,
        "State"
    ],
    "Dirty": customer_dirty.loc[
        state_abbreviation_rows,
        "State"
    ]
})

comparison

            Master Dirty
204      Karnataka    KA
220         Kerala    KL
511  Uttar Pradesh    UP
29       Telangana    TS
222    West Bengal    WB
414      Telangana    TS
509    Maharashtra    MH
318      Karnataka    KA
339     Tamil Nadu    TN
200     Tamil Nadu    TN
136          Delhi    DL
473     Tamil Nadu    TN
47       Karnataka    KA
575     Tamil Nadu    TN
280      Karnataka    KA
254      Karnataka    KA
563         Kerala    KL
437  Uttar Pradesh    UP
381     Chandigarh    CH
287    Maharashtra    MH

In [95]:
(
    customer_master.loc[state_abbreviation_rows, "State"]
    !=
    customer_dirty.loc[state_abbreviation_rows, "State"]
).sum()

20

In [96]:
len(set(state_abbreviation_rows) & used_rows)

0

In [97]:
used_rows.update(state_abbreviation_rows)

In [98]:
len(used_rows)

145

In [99]:
#CELL 24 - SELECT ROWS FOR Join_Date STORED AS TEXT

available_rows = list(set(customer_dirty.index) - used_rows)

join_date_as_text_rows = random.sample(
    available_rows,
    ERROR_PLAN["join_date_as_text"]
)

In [100]:
len(join_date_as_text_rows)

25

In [101]:
len(set(join_date_as_text_rows))

25

In [102]:
len(set(join_date_as_text_rows) & used_rows)

0

In [103]:
customer_dirty.loc[
    join_date_as_text_rows,
    ["Customer_ID", "Join_Date"]
].head()

    Customer_ID   Join_Date
294       C0295  2025-10-29
28        C0029  2023-12-09
255       C0256  2023-03-30
515       C0516  2023-09-04
425       C0426  2025-07-20

In [104]:
#CELL 25 - CONVERT Join_Date AS TEXT

# ============================================================
# Convert Join_Date to Text
# ============================================================

for row in join_date_as_text_rows:

    original_date = pd.to_datetime(
        customer_master.loc[row, "Join_Date"]
    )

    customer_dirty.loc[row, "Join_Date"] = original_date.strftime("%d-%b-%Y")

In [105]:
comparison = pd.DataFrame({
    "Master": customer_master.loc[
        join_date_as_text_rows,
        "Join_Date"
    ],
    "Dirty": customer_dirty.loc[
        join_date_as_text_rows,
        "Join_Date"
    ]
})

comparison.head(10)

         Master        Dirty
294  2025-10-29  29-Oct-2025
28   2023-12-09  09-Dec-2023
255  2023-03-30  30-Mar-2023
515  2023-09-04  04-Sep-2023
425  2025-07-20  20-Jul-2025
364  2023-11-28  28-Nov-2023
91   2023-01-11  11-Jan-2023
455  2024-04-15  15-Apr-2024
645  2024-04-14  14-Apr-2024
516  2025-11-27  27-Nov-2025

In [106]:
type(customer_dirty.loc[join_date_as_text_rows[0], "Join_Date"])

str

In [107]:
len(set(join_date_as_text_rows) & used_rows)

0

In [108]:
used_rows.update(join_date_as_text_rows)

In [109]:
len(used_rows)

170

In [110]:
#CELL 26 - SELECT ROWS TO DUPLICATE

available_rows = list(set(customer_dirty.index) - used_rows)

duplicate_rows = random.sample(
    available_rows,
    ERROR_PLAN["duplicate_records"]
)

In [111]:
len(duplicate_rows)

10

In [112]:
len(set(duplicate_rows))

10

In [113]:
len(set(duplicate_rows) & used_rows)

0

In [114]:
customer_dirty.loc[
    duplicate_rows
].head()

,Customer_ID,Customer_Name,Gender,Age,City,State,Customer_Segment,Join_Date
156,C0157,Ananya Menon,Female,46,Pune,Maharashtra,Regular,2024-06-23
521,C0522,Aadhya Yadav,Female,38,Surat,Gujarat,Regular,2024-03-07
262,C0263,Krishna Malhotra,Male,55,Kochi,Kerala,Budget,2023-04-25
348,C0349,Arjun Patel,Male,32,Mumbai,Maharashtra,Budget,2024-07-18
64,C0065,Rohan Kapoor,Male,39,Visakhapatnam,Andhra Pradesh,Budget,2023-04-04

In [115]:
#CELL 27 - APPEND DUPLICCATE RECORDS

# ============================================================
# Append Duplicate Records
# ============================================================

duplicate_records = customer_dirty.loc[
    duplicate_rows
].copy()

customer_dirty = pd.concat(
    [customer_dirty, duplicate_records],
    ignore_index=True
)

# ============================================================
# Shuffle Dataset (Realistic Duplicate Distribution)
# ============================================================

customer_dirty = customer_dirty.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [116]:
customer_dirty.shape

(760, 8)

In [117]:
customer_dirty.duplicated().sum()

10

In [118]:
duplicate_customer_ids = (
    customer_dirty["Customer_ID"]
    .value_counts()
    .loc[lambda x: x == 2]
)

duplicate_customer_ids

Customer_ID
C0065    2
C0522    2
C0157    2
C0689    2
C0263    2
C0582    2
C0349    2
C0270    2
C0713    2
C0002    2
Name: count, dtype: int64

In [119]:
customer_dirty[
    customer_dirty["Customer_ID"].isin(duplicate_customer_ids.index)
].sort_values("Customer_ID")

,Customer_ID,Customer_Name,Gender,Age,City,State,Customer_Segment,Join_Date
102,C0002,Vivaan Jain,Male,26,Visakhapatnam,Andhra Pradesh,Budget,2023-01-19
691,C0002,Vivaan Jain,Male,26,Visakhapatnam,Andhra Pradesh,Budget,2023-01-19
667,C0065,Rohan Kapoor,Male,39,Visakhapatnam,Andhra Pradesh,Budget,2023-04-04
471,C0065,Rohan Kapoor,Male,39,Visakhapatnam,Andhra Pradesh,Budget,2023-04-04
669,C0157,Ananya Menon,Female,46,Pune,Maharashtra,Regular,2024-06-23
353,C0157,Ananya Menon,Female,46,Pune,Maharashtra,Regular,2024-06-23
225,C0263,Krishna Malhotra,Male,55,Kochi,Kerala,Budget,2023-04-25
541,C0263,Krishna Malhotra,Male,55,Kochi,Kerala,Budget,2023-04-25
682,C0270,Nikhil Sinha,Male,31,Chennai,Tamil Nadu,Premium,2024-08-03
366,C0270,Nikhil Sinha,Male,31,Chennai,Tamil Nadu,Premium,2024-08-03
712,C0349,Arjun Patel,Male,32,Mumbai,Maharashtra,Budget,2024-07-18
553,C0349,Arjun Patel,Male,32,Mumbai,Maharashtra,Budget,2024-07-18
418,C0522,Aadhya Yadav,Female,38,Surat,Gujarat,Regular,2024-03-07
338,C0522,Aadhya Yadav,Female,38,Surat,Gujarat,Regular,2024-03-07
579,C0582,Kavya Singh,Female,43,Mumbai,Maharashtra,Regular,2024-06-11
111,C0582,Kavya Singh,Female,43,Mumbai,Maharashtra,Regular,2024-06-11
681,C0689,Ishaan Nair,Male,31,Nagpur,Maharashtra,Regular,2025-10-04
355,C0689,Ishaan Nair,Male,31,Nagpur,Maharashtra,Regular,2025-10-04
71,C0713,Shreya Sinha,Female,47,Bengaluru,Karnataka,Premium,2024-08-06
57,C0713,Shreya Sinha,Female,47,Bengaluru,Karnataka,Premium,2024-08-06

In [120]:
used_rows.update(duplicate_rows)

In [121]:
len(used_rows)

180

In [122]:
#CELL 28 - FINAL VALIDATION SUMMARY

print("=" * 60)
print("CUSTOMER MASTER DIRTY DATASET VALIDATION")
print("=" * 60)

print(f"\nOriginal Rows           : {len(customer_master)}")
print(f"Dirty Dataset Rows      : {len(customer_dirty)}")
print(f"Duplicate Rows Added    : {len(customer_dirty) - len(customer_master)}")

print("\nMissing Values")
print("-" * 60)
print(customer_dirty.isna().sum())

print("\nDuplicate Customer IDs")
print("-" * 60)
duplicate_customer_ids = (
    customer_dirty["Customer_ID"]
    .value_counts()
    .loc[lambda x: x > 1]
)

print(duplicate_customer_ids)

print("\nState Abbreviations")
print("-" * 60)
print(
    customer_dirty["State"]
    .isin(STATE_ABBREVIATIONS.values())
    .sum()
)

print("\nJoin_Date Data Types")
print("-" * 60)
print(customer_dirty["Join_Date"].apply(type).value_counts())

============================================================
CUSTOMER MASTER DIRTY DATASET VALIDATION
============================================================

Original Rows           : 750
Dirty Dataset Rows      : 760
Duplicate Rows Added    : 10

Missing Values
------------------------------------------------------------
Customer_ID          0
Customer_Name        0
Gender               0
Age                  0
City                15
State                0
Customer_Segment     0
Join_Date            0
dtype: int64

Duplicate Customer IDs
------------------------------------------------------------
Customer_ID
C0065    2
C0522    2
C0157    2
C0689    2
C0263    2
C0582    2
C0349    2
C0270    2
C0713    2
C0002    2
Name: count, dtype: int64

State Abbreviations
------------------------------------------------------------
20

Join_Date Data Types
------------------------------------------------------------
Join_Date
<class 'str'>    760
Name: count, dtype: int64

In [123]:
#CELL 29 - EXPORT DIRTY DATASET

customer_dirty.to_csv(
    "Customer_Master_Dirty.csv",
    index=False
)

print("=" * 60)
print("EXPORT SUCCESSFUL")
print("=" * 60)
print("File Saved : Customer_Master_Dirty.csv")
print(f"Total Rows    : {len(customer_dirty)}")
print(f"Total Columns : {customer_dirty.shape[1]}")

============================================================
EXPORT SUCCESSFUL
============================================================
File Saved : Customer_Master_Dirty.csv
Total Rows    : 760
Total Columns : 8

In [124]:
#CELL 30 - NOTEBOOK COMPLETION SUMMARY

print("=" * 60)
print("NOTEBOOK COMPLETED SUCCESSFULLY")
print("=" * 60)

print("""
Customer_Master_Dirty.xlsx has been generated successfully.

Injected Error Types
--------------------
✔ Leading & Trailing Spaces
✔ Double Spaces
✔ Mixed Capitalization
✔ ALL CAPS
✔ all lowercase
✔ Hidden Characters
✔ Blank City
✔ State Abbreviations
✔ Join_Date stored as Text
✔ Duplicate Records

The master dataset remains unchanged.

The dirty dataset is now ready for Microsoft Excel data cleaning.
""")

============================================================
NOTEBOOK COMPLETED SUCCESSFULLY
============================================================

Customer_Master_Dirty.xlsx has been generated successfully.

Injected Error Types
--------------------
✔ Leading & Trailing Spaces
✔ Double Spaces
✔ Mixed Capitalization
✔ ALL CAPS
✔ all lowercase
✔ Hidden Characters
✔ Blank City
✔ State Abbreviations
✔ Join_Date stored as Text
✔ Duplicate Records

The master dataset remains unchanged.

The dirty dataset is now ready for Microsoft Excel data cleaning.