CELL 1 
# FictionalCart Microsoft Excel Capstone Project

# Phase 2 — Dirty Data Generation

## Notebook 04 — Returns_Dirty_Generation.ipynb

### Objective

This notebook generates a dirty version of the Returns dataset for Microsoft Excel data cleaning practice.

The master dataset (`Returns.csv`) remains unchanged throughout the process.

Workflow:

Returns.csv
    ↓
Working Copy
    ↓
Inject Planned Errors
    ↓
Validate Every Error
    ↓
Update Modification Tracker
    ↓
Export Returns_Dirty.csv

This notebook follows the same implementation methodology used in the previous dirty data generation notebooks to ensure consistency across the FictionalCart project.

---

## Frozen Error Plan

| Error Type | Rows |
|------------|-----:|
| Leading Spaces | 8 |
| Trailing Spaces | 8 |
| Double Spaces | 8 |
| ALL CAPS | 8 |
| Lowercase | 8 |
| Mixed Capitalization | 8 |
| Hidden Tabs | 5 |
| Blank Return_Date | 4 |
| Blank Refund_Amount | 4 |
| Blank Return_Reason | 4 |
| Duplicate Records | 10 |

Text Variations have been intentionally skipped because Return_Reason is a controlled business field.

In [1]:
#CELL 2 - IMPORT REQUIRED LIBRARIES

import pandas as pd
import numpy as np
import random

from IPython.display import display

In [2]:
#CELL 3 - FIXED RANDOM SEED

RANDOM_SEED = 42

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

print(f"Random Seed Fixed at: {RANDOM_SEED}")

Random Seed Fixed at: 42

In [3]:
#CELL 4 - LOAD MASTER DATASET

returns_master = pd.read_csv("../01_Master_Datasets/Returns.csv")

returns_dirty = returns_master.copy(deep=True)

print("Master Dataset Loaded Successfully.\n")

print(f"Rows    : {len(returns_master)}")
print(f"Columns : {returns_master.shape[1]}")

Master Dataset Loaded Successfully.

Rows    : 253
Columns : 7

In [4]:
#CELL 5 - INITIAL DATASET VALIDATION

print("=" * 60)
print("RETURNS DATASET INFORMATION")
print("=" * 60)

display(returns_dirty.head())

print("\nColumn Information\n")
print(returns_dirty.dtypes)

print("\nMissing Values\n")
print(returns_dirty.isna().sum())

============================================================
RETURNS DATASET INFORMATION
============================================================

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
0,R00001,O000002,C0590,P0119,2025-12-10,Changed Mind,1560
1,R00002,O000003,C0399,P0118,2025-07-17,Damaged Product,310
2,R00003,O000076,C0189,P0169,2025-10-21,Other,11260
3,R00004,O000078,C0441,P0006,2025-02-26,Damaged Product,76230
4,R00005,O000122,C0607,P0021,2025-10-28,Late Delivery,101670

Column Information

Return_ID        object
Order_ID         object
Customer_ID      object
Product_ID       object
Return_Date      object
Return_Reason    object
Refund_Amount     int64
dtype: object

Missing Values

Return_ID        0
Order_ID         0
Customer_ID      0
Product_ID       0
Return_Date      0
Return_Reason    0
Refund_Amount    0
dtype: int64

In [5]:
#CELL 6 - INITIALIZE MODIFICATION TRACKER

modified_rows = set()

print("Modification Tracker Initialized.")

print(f"Modified Rows : {len(modified_rows)}")

Modification Tracker Initialized.
Modified Rows : 0

In [6]:
#CELL 7 - LEADING SPACES IMPLEMENTAION

print("=" * 60)
print("Injecting Leading Spaces")
print("=" * 60)

ERROR_COUNT = 8

# Select only rows that have not been modified
available_rows = list(set(returns_dirty.index) - modified_rows)

selected_rows = random.sample(available_rows, ERROR_COUNT)

# Store original values for validation
leading_spaces_original = returns_dirty.loc[
    selected_rows,
    "Return_Reason"
].copy()

# Inject leading spaces
returns_dirty.loc[
    selected_rows,
    "Return_Reason"
] = (
    "   " +
    returns_dirty.loc[selected_rows, "Return_Reason"].astype(str)
)

print(f"Selected Rows : {len(selected_rows)}")
print("Leading spaces injected successfully.")

============================================================
Injecting Leading Spaces
============================================================
Selected Rows : 8
Leading spaces injected successfully.

In [7]:
#CELL 8 - LEADING SPACES VALIDATION

print("=" * 60)
print("LEADING SPACES VALIDATION")
print("=" * 60)

actual_count = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .str.startswith("   ")
    .sum()
)

print(f"Expected Rows : {ERROR_COUNT}")
print(f"Actual Rows   : {actual_count}")

assert actual_count == ERROR_COUNT

print("\nFirst Five Before vs After\n")

for i in range(min(5, ERROR_COUNT)):
    row = selected_rows[i]

    print(f"Row Index : {row}")

    print("Before :", repr(leading_spaces_original.loc[row]))
    print("After  :", repr(returns_dirty.loc[row, "Return_Reason"]))
    print("-" * 50)

print("\nSample Modified Rows\n")

display(
    returns_dirty.loc[
        selected_rows[:5]
    ]
)

print("SUCCESS: Leading Spaces Validation Passed")

============================================================
LEADING SPACES VALIDATION
============================================================
Expected Rows : 8
Actual Rows   : 8

First Five Before vs After

Row Index : 163
Before : 'Late Delivery'
After  : '   Late Delivery'
--------------------------------------------------
Row Index : 28
Before : 'Damaged Product'
After  : '   Damaged Product'
--------------------------------------------------
Row Index : 6
Before : 'Damaged Product'
After  : '   Damaged Product'
--------------------------------------------------
Row Index : 189
Before : 'Damaged Product'
After  : '   Damaged Product'
--------------------------------------------------
Row Index : 70
Before : 'Other'
After  : '   Other'
--------------------------------------------------

Sample Modified Rows

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
163,R00164,O003256,C0189,P0179,2025-01-30,Late Delivery,240
28,R00029,O000540,C0034,P0121,2025-10-23,Damaged Product,620
6,R00007,O000157,C0223,P0162,2024-12-13,Damaged Product,6680
189,R00190,O003829,C0180,P0071,2025-09-16,Damaged Product,2870
70,R00071,O001457,C0742,P0058,2024-11-09,Other,4800

SUCCESS: Leading Spaces Validation Passed

In [8]:
#CELL 9 - TRACKER UPDATE

previous_count = len(modified_rows)

modified_rows.update(selected_rows)

current_count = len(modified_rows)

print("=" * 60)
print("TRACKER VALIDATION")
print("=" * 60)

print(f"Previous Count : {previous_count}")
print(f"Rows Added     : {ERROR_COUNT}")
print(f"Current Count  : {current_count}")

assert current_count == previous_count + ERROR_COUNT

print("\nSUCCESS: Modification Tracker Updated Successfully")

============================================================
TRACKER VALIDATION
============================================================
Previous Count : 0
Rows Added     : 8
Current Count  : 8

SUCCESS: Modification Tracker Updated Successfully

In [9]:
#CELL 10 - TRAILING SPACES IMPLEMENTATION

print("=" * 60)
print("Injecting Trailing Spaces")
print("=" * 60)

ERROR_COUNT = 8

# Select only rows that have not been modified
available_rows = list(set(returns_dirty.index) - modified_rows)

selected_rows = random.sample(available_rows, ERROR_COUNT)

# Store original values for validation
trailing_spaces_original = returns_dirty.loc[
    selected_rows,
    "Return_Reason"
].copy()

# Inject trailing spaces
returns_dirty.loc[
    selected_rows,
    "Return_Reason"
] = (
    returns_dirty.loc[selected_rows, "Return_Reason"].astype(str)
    + "   "
)

print(f"Selected Rows : {len(selected_rows)}")
print("Trailing spaces injected successfully.")

============================================================
Injecting Trailing Spaces
============================================================
Selected Rows : 8
Trailing spaces injected successfully.

In [10]:
#CELL 11 - TRAILING SPACES VALIDATION

print("=" * 60)
print("TRAILING SPACES VALIDATION")
print("=" * 60)

actual_count = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .str.endswith("   ")
    .sum()
)

print(f"Expected Rows : {ERROR_COUNT}")
print(f"Actual Rows   : {actual_count}")

assert actual_count == ERROR_COUNT

print("\nFirst Five Before vs After\n")

for i in range(min(5, ERROR_COUNT)):
    row = selected_rows[i]

    print(f"Row Index : {row}")

    print("Before :", repr(trailing_spaces_original.loc[row]))
    print("After  :", repr(returns_dirty.loc[row, "Return_Reason"]))
    print("-" * 50)

print("\nSample Modified Rows\n")

display(
    returns_dirty.loc[selected_rows[:5]]
)

print("SUCCESS: Trailing Spaces Validation Passed")

============================================================
TRAILING SPACES VALIDATION
============================================================
Expected Rows : 8
Actual Rows   : 8

First Five Before vs After

Row Index : 196
Before : 'Damaged Product'
After  : 'Damaged Product   '
--------------------------------------------------
Row Index : 27
Before : 'Wrong Item Received'
After  : 'Wrong Item Received   '
--------------------------------------------------
Row Index : 180
Before : 'Late Delivery'
After  : 'Late Delivery   '
--------------------------------------------------
Row Index : 197
Before : 'Changed Mind'
After  : 'Changed Mind   '
--------------------------------------------------
Row Index : 236
Before : 'Damaged Product'
After  : 'Damaged Product   '
--------------------------------------------------

Sample Modified Rows

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
196,R00197,O003899,C0363,P0014,2023-03-05,Damaged Product,26790
27,R00028,O000518,C0405,P0173,2025-11-03,Wrong Item Received,3360
180,R00181,O003604,C0280,P0088,2025-05-05,Late Delivery,1900
197,R00198,O003912,C0676,P0170,2023-12-30,Changed Mind,60800
236,R00237,O004673,C0699,P0003,2024-08-04,Damaged Product,38340

SUCCESS: Trailing Spaces Validation Passed

In [11]:
#CELL 12 - TRACKER UPDATE

previous_count = len(modified_rows)

modified_rows.update(selected_rows)

current_count = len(modified_rows)

print("=" * 60)
print("TRACKER VALIDATION")
print("=" * 60)

print(f"Previous Count : {previous_count}")
print(f"Rows Added     : {ERROR_COUNT}")
print(f"Current Count  : {current_count}")

assert current_count == previous_count + ERROR_COUNT

print("\nSUCCESS: Modification Tracker Updated Successfully")

============================================================
TRACKER VALIDATION
============================================================
Previous Count : 8
Rows Added     : 8
Current Count  : 16

SUCCESS: Modification Tracker Updated Successfully

In [12]:
#CELL 13 - DOUBLE SPACES IMPLEMENTATION

print("=" * 60)
print("Injecting Double Spaces")
print("=" * 60)

ERROR_COUNT = 8

# Select only rows that have not been modified
available_rows = list(set(returns_dirty.index) - modified_rows)

selected_rows = random.sample(available_rows, ERROR_COUNT)

# Store original values for validation
double_spaces_original = returns_dirty.loc[
    selected_rows,
    "Return_Reason"
].copy()

# Inject multiple spaces between words
returns_dirty.loc[
    selected_rows,
    "Return_Reason"
] = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .astype(str)
    .str.replace(" ", "   ", n=1, regex=False)
)

print(f"Selected Rows : {len(selected_rows)}")
print("Double spaces injected successfully.")

============================================================
Injecting Double Spaces
============================================================
Selected Rows : 8
Double spaces injected successfully.

In [13]:
#CELL 14 - DOUBLE SPACES VALIDATION

print("=" * 60)
print("DOUBLE SPACES VALIDATION")
print("=" * 60)

actual_count = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .str.contains("   ", regex=False)
    .sum()
)

print(f"Expected Rows : {ERROR_COUNT}")
print(f"Actual Rows   : {actual_count}")

assert actual_count == ERROR_COUNT

print("\nFirst Five Before vs After\n")

for i in range(min(5, ERROR_COUNT)):
    row = selected_rows[i]

    print(f"Row Index : {row}")

    print("Before :", repr(double_spaces_original.loc[row]))
    print("After  :", repr(returns_dirty.loc[row, "Return_Reason"]))
    print("-" * 50)

print("\nSample Modified Rows\n")

display(
    returns_dirty.loc[selected_rows[:5]]
)

print("SUCCESS: Double Spaces Validation Passed")

============================================================
DOUBLE SPACES VALIDATION
============================================================
Expected Rows : 8
Actual Rows   : 8

First Five Before vs After

Row Index : 116
Before : 'Damaged Product'
After  : 'Damaged   Product'
--------------------------------------------------
Row Index : 9
Before : 'Changed Mind'
After  : 'Changed   Mind'
--------------------------------------------------
Row Index : 8
Before : 'Defective Product'
After  : 'Defective   Product'
--------------------------------------------------
Row Index : 25
Before : 'Changed Mind'
After  : 'Changed   Mind'
--------------------------------------------------
Row Index : 61
Before : 'Defective Product'
After  : 'Defective   Product'
--------------------------------------------------

Sample Modified Rows

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
116,R00117,O002274,C0111,P0146,2025-11-29,Damaged Product,1000
9,R00010,O000213,C0488,P0121,2025-04-19,Changed Mind,620
8,R00009,O000198,C0260,P0116,2023-10-26,Defective Product,260
25,R00026,O000483,C0378,P0094,2025-10-19,Changed Mind,23650
61,R00062,O001316,C0456,P0141,2024-01-29,Defective Product,980

SUCCESS: Double Spaces Validation Passed

In [14]:
#CELL 15 - TRACKER UPDATE

previous_count = len(modified_rows)

modified_rows.update(selected_rows)

current_count = len(modified_rows)

print("=" * 60)
print("TRACKER VALIDATION")
print("=" * 60)

print(f"Previous Count : {previous_count}")
print(f"Rows Added     : {ERROR_COUNT}")
print(f"Current Count  : {current_count}")

assert current_count == previous_count + ERROR_COUNT

print("\nSUCCESS: Modification Tracker Updated Successfully")

============================================================
TRACKER VALIDATION
============================================================
Previous Count : 16
Rows Added     : 8
Current Count  : 24

SUCCESS: Modification Tracker Updated Successfully

In [15]:
#CELL 16 - ALL CAPS

print("=" * 60)
print("Injecting ALL CAPS")
print("=" * 60)

ERROR_COUNT = 8

# Select only rows that have not been modified
available_rows = list(set(returns_dirty.index) - modified_rows)

selected_rows = random.sample(available_rows, ERROR_COUNT)

# Store original values for validation
all_caps_original = returns_dirty.loc[
    selected_rows,
    "Return_Reason"
].copy()

# Convert text to ALL CAPS
returns_dirty.loc[
    selected_rows,
    "Return_Reason"
] = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .astype(str)
    .str.upper()
)

print(f"Selected Rows : {len(selected_rows)}")
print("ALL CAPS injected successfully.")

============================================================
Injecting ALL CAPS
============================================================
Selected Rows : 8
ALL CAPS injected successfully.

In [16]:
#CELL 17 - ALL CAPS

print("=" * 60)
print("ALL CAPS VALIDATION")
print("=" * 60)

actual_count = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .eq(
        returns_dirty.loc[selected_rows, "Return_Reason"].str.upper()
    )
    .sum()
)

print(f"Expected Rows : {ERROR_COUNT}")
print(f"Actual Rows   : {actual_count}")

assert actual_count == ERROR_COUNT

print("\nFirst Five Before vs After\n")

for i in range(min(5, ERROR_COUNT)):
    row = selected_rows[i]

    print(f"Row Index : {row}")

    print("Before :", repr(all_caps_original.loc[row]))
    print("After  :", repr(returns_dirty.loc[row, "Return_Reason"]))
    print("-" * 50)

print("\nSample Modified Rows\n")

display(
    returns_dirty.loc[selected_rows[:5]]
)

print("SUCCESS: ALL CAPS Validation Passed")

============================================================
ALL CAPS VALIDATION
============================================================
Expected Rows : 8
Actual Rows   : 8

First Five Before vs After

Row Index : 7
Before : 'Wrong Item Received'
After  : 'WRONG ITEM RECEIVED'
--------------------------------------------------
Row Index : 160
Before : 'Changed Mind'
After  : 'CHANGED MIND'
--------------------------------------------------
Row Index : 59
Before : 'Late Delivery'
After  : 'LATE DELIVERY'
--------------------------------------------------
Row Index : 206
Before : 'Damaged Product'
After  : 'DAMAGED PRODUCT'
--------------------------------------------------
Row Index : 186
Before : 'Damaged Product'
After  : 'DAMAGED PRODUCT'
--------------------------------------------------

Sample Modified Rows

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
7,R00008,O000187,C0204,P0114,2025-07-30,WRONG ITEM RECEIVED,4770
160,R00161,O003187,C0293,P0029,2025-12-19,CHANGED MIND,47820
59,R00060,O001290,C0376,P0090,2025-06-03,LATE DELIVERY,9260
206,R00207,O004091,C0733,P0191,2025-12-01,DAMAGED PRODUCT,1080
186,R00187,O003756,C0713,P0104,2024-08-25,DAMAGED PRODUCT,8190

SUCCESS: ALL CAPS Validation Passed

In [17]:
#CELL 18 - TRACKER UPDATE

previous_count = len(modified_rows)

modified_rows.update(selected_rows)

current_count = len(modified_rows)

print("=" * 60)
print("TRACKER VALIDATION")
print("=" * 60)

print(f"Previous Count : {previous_count}")
print(f"Rows Added     : {ERROR_COUNT}")
print(f"Current Count  : {current_count}")

assert current_count == previous_count + ERROR_COUNT

print("\nSUCCESS: Modification Tracker Updated Successfully")

============================================================
TRACKER VALIDATION
============================================================
Previous Count : 24
Rows Added     : 8
Current Count  : 32

SUCCESS: Modification Tracker Updated Successfully

In [18]:
#CELL 19 - LOWERCASE IMPLEMENTATION

print("=" * 60)
print("Injecting Lowercase")
print("=" * 60)

ERROR_COUNT = 8

# Select only rows that have not been modified
available_rows = list(set(returns_dirty.index) - modified_rows)

selected_rows = random.sample(available_rows, ERROR_COUNT)

# Store original values for validation
lowercase_original = returns_dirty.loc[
    selected_rows,
    "Return_Reason"
].copy()

# Convert text to lowercase
returns_dirty.loc[
    selected_rows,
    "Return_Reason"
] = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .astype(str)
    .str.lower()
)

print(f"Selected Rows : {len(selected_rows)}")
print("Lowercase injected successfully.")

============================================================
Injecting Lowercase
============================================================
Selected Rows : 8
Lowercase injected successfully.

In [19]:
#CELL 20 - LOWERCASE VALIDATION

print("=" * 60)
print("LOWERCASE VALIDATION")
print("=" * 60)

actual_count = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .eq(
        returns_dirty.loc[selected_rows, "Return_Reason"].str.lower()
    )
    .sum()
)

print(f"Expected Rows : {ERROR_COUNT}")
print(f"Actual Rows   : {actual_count}")

assert actual_count == ERROR_COUNT

print("\nFirst Five Before vs After\n")

for i in range(min(5, ERROR_COUNT)):
    row = selected_rows[i]

    print(f"Row Index : {row}")

    print("Before :", repr(lowercase_original.loc[row]))
    print("After  :", repr(returns_dirty.loc[row, "Return_Reason"]))
    print("-" * 50)

print("\nSample Modified Rows\n")

display(
    returns_dirty.loc[selected_rows[:5]]
)

print("SUCCESS: Lowercase Validation Passed")

============================================================
LOWERCASE VALIDATION
============================================================
Expected Rows : 8
Actual Rows   : 8

First Five Before vs After

Row Index : 71
Before : 'Damaged Product'
After  : 'damaged product'
--------------------------------------------------
Row Index : 131
Before : 'Damaged Product'
After  : 'damaged product'
--------------------------------------------------
Row Index : 174
Before : 'Damaged Product'
After  : 'damaged product'
--------------------------------------------------
Row Index : 86
Before : 'Size/Fit Issue'
After  : 'size/fit issue'
--------------------------------------------------
Row Index : 239
Before : 'Wrong Item Received'
After  : 'wrong item received'
--------------------------------------------------

Sample Modified Rows

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
71,R00072,O001483,C0325,P0018,2024-09-12,damaged product,9650
131,R00132,O002636,C0066,P0084,2025-11-26,damaged product,2470
174,R00175,O003487,C0375,P0025,2024-03-04,damaged product,70360
86,R00087,O001716,C0641,P0075,2023-09-08,size/fit issue,2580
239,R00240,O004713,C0519,P0199,2023-08-15,wrong item received,4660

SUCCESS: Lowercase Validation Passed

In [20]:
#CELL 21 - TRACKER UPDATE

previous_count = len(modified_rows)

modified_rows.update(selected_rows)

current_count = len(modified_rows)

print("=" * 60)
print("TRACKER VALIDATION")
print("=" * 60)

print(f"Previous Count : {previous_count}")
print(f"Rows Added     : {ERROR_COUNT}")
print(f"Current Count  : {current_count}")

assert current_count == previous_count + ERROR_COUNT

print("\nSUCCESS: Modification Tracker Updated Successfully")

============================================================
TRACKER VALIDATION
============================================================
Previous Count : 32
Rows Added     : 8
Current Count  : 40

SUCCESS: Modification Tracker Updated Successfully

In [21]:
#CELL 22 - MIXED CAPITALIZATION IMPLEMENTATION

print("=" * 60)
print("Injecting Mixed Capitalization")
print("=" * 60)

ERROR_COUNT = 8

# Select only rows that have not been modified
available_rows = list(set(returns_dirty.index) - modified_rows)

selected_rows = random.sample(available_rows, ERROR_COUNT)

# Store original values for validation
mixed_case_original = returns_dirty.loc[
    selected_rows,
    "Return_Reason"
].copy()


def alternating_case(text):
    result = []

    for i, char in enumerate(str(text)):
        if char.isalpha():
            if i % 2 == 0:
                result.append(char.upper())
            else:
                result.append(char.lower())
        else:
            result.append(char)

    return "".join(result)


returns_dirty.loc[
    selected_rows,
    "Return_Reason"
] = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .apply(alternating_case)
)

print(f"Selected Rows : {len(selected_rows)}")
print("Mixed capitalization injected successfully.")

============================================================
Injecting Mixed Capitalization
============================================================
Selected Rows : 8
Mixed capitalization injected successfully.

In [22]:
#CELL 23 - MIXED CAPITALIZATION VALIDATION

print("=" * 60)
print("MIXED CAPITALIZATION VALIDATION")
print("=" * 60)

expected_values = mixed_case_original.apply(alternating_case)

actual_count = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .eq(expected_values)
    .sum()
)

print(f"Expected Rows : {ERROR_COUNT}")
print(f"Actual Rows   : {actual_count}")

assert actual_count == ERROR_COUNT

print("\nFirst Five Before vs After\n")

for i in range(min(5, ERROR_COUNT)):
    row = selected_rows[i]

    print(f"Row Index : {row}")

    print("Before :", repr(mixed_case_original.loc[row]))
    print("After  :", repr(returns_dirty.loc[row, "Return_Reason"]))
    print("-" * 50)

print("\nSample Modified Rows\n")

display(
    returns_dirty.loc[selected_rows[:5]]
)

print("SUCCESS: Mixed Capitalization Validation Passed")

============================================================
MIXED CAPITALIZATION VALIDATION
============================================================
Expected Rows : 8
Actual Rows   : 8

First Five Before vs After

Row Index : 50
Before : 'Size/Fit Issue'
After  : 'SiZe/fIt iSsUe'
--------------------------------------------------
Row Index : 214
Before : 'Size/Fit Issue'
After  : 'SiZe/fIt iSsUe'
--------------------------------------------------
Row Index : 128
Before : 'Wrong Item Received'
After  : 'WrOnG ItEm rEcEiVeD'
--------------------------------------------------
Row Index : 105
Before : 'Defective Product'
After  : 'DeFeCtIvE PrOdUcT'
--------------------------------------------------
Row Index : 89
Before : 'Defective Product'
After  : 'DeFeCtIvE PrOdUcT'
--------------------------------------------------

Sample Modified Rows

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
50,R00051,O001047,C0234,P0001,2024-05-14,SiZe/fIt iSsUe,35640
214,R00215,O004169,C0454,P0146,2024-01-05,SiZe/fIt iSsUe,1000
128,R00129,O002573,C0418,P0149,2025-08-21,WrOnG ItEm rEcEiVeD,2880
105,R00106,O002027,C0253,P0110,2025-06-29,DeFeCtIvE PrOdUcT,7680
89,R00090,O001754,C0320,P0107,2025-07-07,DeFeCtIvE PrOdUcT,20820

SUCCESS: Mixed Capitalization Validation Passed

In [23]:
#CELL 24 - TRACKER UPDATE

previous_count = len(modified_rows)

modified_rows.update(selected_rows)

current_count = len(modified_rows)

print("=" * 60)
print("TRACKER VALIDATION")
print("=" * 60)

print(f"Previous Count : {previous_count}")
print(f"Rows Added     : {ERROR_COUNT}")
print(f"Current Count  : {current_count}")

assert current_count == previous_count + ERROR_COUNT

print("\nSUCCESS: Modification Tracker Updated Successfully")

============================================================
TRACKER VALIDATION
============================================================
Previous Count : 40
Rows Added     : 8
Current Count  : 48

SUCCESS: Modification Tracker Updated Successfully

In [24]:
#CELL 25 - HIDDEN TABS IMPLEMENTATION

print("=" * 60)
print("Injecting Hidden Tabs")
print("=" * 60)

ERROR_COUNT = 5

# Select only rows that have not been modified
available_rows = list(set(returns_dirty.index) - modified_rows)

selected_rows = random.sample(available_rows, ERROR_COUNT)

# Store original values for validation
hidden_tabs_original = returns_dirty.loc[
    selected_rows,
    "Return_Reason"
].copy()

# Inject hidden tab after the first word
returns_dirty.loc[
    selected_rows,
    "Return_Reason"
] = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .astype(str)
    .str.replace(" ", "\t", n=1, regex=False)
)

print(f"Selected Rows : {len(selected_rows)}")
print("Hidden tabs injected successfully.")

============================================================
Injecting Hidden Tabs
============================================================
Selected Rows : 5
Hidden tabs injected successfully.

In [25]:
#CELL 26 - HIDDEN TABS VALIDATION

print("=" * 60)
print("HIDDEN TABS VALIDATION")
print("=" * 60)

actual_count = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .str.contains("\t", regex=False)
    .sum()
)

print(f"Expected Rows : {ERROR_COUNT}")
print(f"Actual Rows   : {actual_count}")

assert actual_count == ERROR_COUNT

print("\nFirst Five Before vs After\n")

for i in range(min(5, ERROR_COUNT)):
    row = selected_rows[i]

    print(f"Row Index : {row}")

    print("Before :", repr(hidden_tabs_original.loc[row]))
    print("After  :", repr(returns_dirty.loc[row, "Return_Reason"]))
    print("-" * 50)

print("\nSample Modified Rows\n")

display(
    returns_dirty.loc[selected_rows[:5]]
)

print("SUCCESS: Hidden Tabs Validation Passed")

============================================================
HIDDEN TABS VALIDATION
============================================================
Expected Rows : 5
Actual Rows   : 5

First Five Before vs After

Row Index : 109
Before : 'Damaged Product'
After  : 'Damaged\tProduct'
--------------------------------------------------
Row Index : 36
Before : 'Size/Fit Issue'
After  : 'Size/Fit\tIssue'
--------------------------------------------------
Row Index : 32
Before : 'Damaged Product'
After  : 'Damaged\tProduct'
--------------------------------------------------
Row Index : 122
Before : 'Wrong Item Received'
After  : 'Wrong\tItem Received'
--------------------------------------------------
Row Index : 33
Before : 'Late Delivery'
After  : 'Late\tDelivery'
--------------------------------------------------

Sample Modified Rows

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
109,R00110,O002081,C0346,P0021,2026-01-13,Damaged\tProduct,67780
36,R00037,O000722,C0393,P0158,2024-05-04,Size/Fit\tIssue,1040
32,R00033,O000658,C0442,P0109,2025-04-06,Damaged\tProduct,6470
122,R00123,O002398,C0008,P0104,2025-09-28,Wrong\tItem Received,2730
33,R00034,O000673,C0152,P0038,2025-08-05,Late\tDelivery,37680

SUCCESS: Hidden Tabs Validation Passed

In [26]:
#CELL 27 - TRACKER UPDATE

previous_count = len(modified_rows)

modified_rows.update(selected_rows)

current_count = len(modified_rows)

print("=" * 60)
print("TRACKER VALIDATION")
print("=" * 60)

print(f"Previous Count : {previous_count}")
print(f"Rows Added     : {ERROR_COUNT}")
print(f"Current Count  : {current_count}")

assert current_count == previous_count + ERROR_COUNT

print("\nSUCCESS: Modification Tracker Updated Successfully")

============================================================
TRACKER VALIDATION
============================================================
Previous Count : 48
Rows Added     : 5
Current Count  : 53

SUCCESS: Modification Tracker Updated Successfully

In [27]:
#CELL 28 - BLANK Return_Date IMPLEMENTATION

print("=" * 60)
print("Injecting Blank Return_Date")
print("=" * 60)

ERROR_COUNT = 4

# Select only rows that have not been modified
available_rows = list(set(returns_dirty.index) - modified_rows)

selected_rows = random.sample(available_rows, ERROR_COUNT)

# Store original values for validation
blank_return_date_original = returns_dirty.loc[
    selected_rows,
    "Return_Date"
].copy()

# Inject blank values
returns_dirty.loc[
    selected_rows,
    "Return_Date"
] = np.nan

print(f"Selected Rows : {len(selected_rows)}")
print("Blank Return_Date values injected successfully.")

============================================================
Injecting Blank Return_Date
============================================================
Selected Rows : 4
Blank Return_Date values injected successfully.

In [28]:
#CELL 29 - BLANK Return_Date VALIDATION

print("=" * 60)
print("BLANK RETURN_DATE VALIDATION")
print("=" * 60)

actual_count = (
    returns_dirty.loc[selected_rows, "Return_Date"]
    .isna()
    .sum()
)

print(f"Expected Rows : {ERROR_COUNT}")
print(f"Actual Rows   : {actual_count}")

assert actual_count == ERROR_COUNT

print("\nFirst Five Before vs After\n")

for i in range(min(5, ERROR_COUNT)):
    row = selected_rows[i]

    print(f"Row Index : {row}")

    print("Before :", repr(blank_return_date_original.loc[row]))
    print("After  :", repr(returns_dirty.loc[row, "Return_Date"]))
    print("-" * 50)

print("\nSample Modified Rows\n")

display(
    returns_dirty.loc[selected_rows]
)

print("SUCCESS: Blank Return_Date Validation Passed")

============================================================
BLANK RETURN_DATE VALIDATION
============================================================
Expected Rows : 4
Actual Rows   : 4

First Five Before vs After

Row Index : 119
Before : '2023-09-25'
After  : nan
--------------------------------------------------
Row Index : 115
Before : '2025-08-29'
After  : nan
--------------------------------------------------
Row Index : 199
Before : '2024-09-16'
After  : nan
--------------------------------------------------
Row Index : 92
Before : '2024-11-29'
After  : nan
--------------------------------------------------

Sample Modified Rows

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
119,R00120,O002350,C0400,P0170,NaN,Wrong Item Received,12160
115,R00116,O002273,C0583,P0096,NaN,Late Delivery,2850
199,R00200,O003962,C0734,P0095,NaN,Wrong Item Received,2340
92,R00093,O001806,C0298,P0066,NaN,Damaged Product,1650

SUCCESS: Blank Return_Date Validation Passed

In [29]:
#CELL 30 - TRACKER UPDATE

previous_count = len(modified_rows)

modified_rows.update(selected_rows)

current_count = len(modified_rows)

print("=" * 60)
print("TRACKER VALIDATION")
print("=" * 60)

print(f"Previous Count : {previous_count}")
print(f"Rows Added     : {ERROR_COUNT}")
print(f"Current Count  : {current_count}")

assert current_count == previous_count + ERROR_COUNT

print("\nSUCCESS: Modification Tracker Updated Successfully")

============================================================
TRACKER VALIDATION
============================================================
Previous Count : 53
Rows Added     : 4
Current Count  : 57

SUCCESS: Modification Tracker Updated Successfully

In [30]:
#CELL 31 - BLANK Refund_Amount IMPLEMENTATION

print("=" * 60)
print("Injecting Blank Refund_Amount")
print("=" * 60)

ERROR_COUNT = 4

# Select only rows that have not been modified
available_rows = list(set(returns_dirty.index) - modified_rows)

selected_rows = random.sample(available_rows, ERROR_COUNT)

# Store original values for validation
blank_refund_original = returns_dirty.loc[
    selected_rows,
    "Refund_Amount"
].copy()

# Inject blank values
returns_dirty.loc[
    selected_rows,
    "Refund_Amount"
] = np.nan

print(f"Selected Rows : {len(selected_rows)}")
print("Blank Refund_Amount values injected successfully.")

============================================================
Injecting Blank Refund_Amount
============================================================
Selected Rows : 4
Blank Refund_Amount values injected successfully.

In [31]:
#CELL 32 - BLANK Refund_Amount VALIDATION

print("=" * 60)
print("BLANK REFUND_AMOUNT VALIDATION")
print("=" * 60)

actual_count = (
    returns_dirty.loc[selected_rows, "Refund_Amount"]
    .isna()
    .sum()
)

print(f"Expected Rows : {ERROR_COUNT}")
print(f"Actual Rows   : {actual_count}")

assert actual_count == ERROR_COUNT

print("\nFirst Five Before vs After\n")

for i in range(min(5, ERROR_COUNT)):
    row = selected_rows[i]

    print(f"Row Index : {row}")

    print("Before :", repr(blank_refund_original.loc[row]))
    print("After  :", repr(returns_dirty.loc[row, "Refund_Amount"]))
    print("-" * 50)

print("\nSample Modified Rows\n")

display(
    returns_dirty.loc[selected_rows]
)

print("SUCCESS: Blank Refund_Amount Validation Passed")

============================================================
BLANK REFUND_AMOUNT VALIDATION
============================================================
Expected Rows : 4
Actual Rows   : 4

First Five Before vs After

Row Index : 16
Before : 4690
After  : nan
--------------------------------------------------
Row Index : 243
Before : 37680
After  : nan
--------------------------------------------------
Row Index : 154
Before : 4200
After  : nan
--------------------------------------------------
Row Index : 181
Before : 1190
After  : nan
--------------------------------------------------

Sample Modified Rows

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
16,R00017,O000335,C0563,P0059,2024-06-03,Damaged Product,NaN
243,R00244,O004747,C0344,P0038,2025-08-26,Late Delivery,NaN
154,R00155,O003072,C0628,P0048,2023-07-26,Damaged Product,NaN
181,R00182,O003609,C0577,P0122,2023-02-06,Defective Product,NaN

SUCCESS: Blank Refund_Amount Validation Passed

In [32]:
#CELL 33 - TRACKER UPDATE

previous_count = len(modified_rows)

modified_rows.update(selected_rows)

current_count = len(modified_rows)

print("=" * 60)
print("TRACKER VALIDATION")
print("=" * 60)

print(f"Previous Count : {previous_count}")
print(f"Rows Added     : {ERROR_COUNT}")
print(f"Current Count  : {current_count}")

assert current_count == previous_count + ERROR_COUNT

print("\nSUCCESS: Modification Tracker Updated Successfully")

============================================================
TRACKER VALIDATION
============================================================
Previous Count : 57
Rows Added     : 4
Current Count  : 61

SUCCESS: Modification Tracker Updated Successfully

In [33]:
#CELL 34 - BLANK Return_Reason IMPLEMENTATION

print("=" * 60)
print("Injecting Blank Return_Reason")
print("=" * 60)

ERROR_COUNT = 4

# Select only rows that have not been modified
available_rows = list(set(returns_dirty.index) - modified_rows)

selected_rows = random.sample(available_rows, ERROR_COUNT)

# Store original values for validation
blank_reason_original = returns_dirty.loc[
    selected_rows,
    "Return_Reason"
].copy()

# Inject blank values
returns_dirty.loc[
    selected_rows,
    "Return_Reason"
] = np.nan

print(f"Selected Rows : {len(selected_rows)}")
print("Blank Return_Reason values injected successfully.")

============================================================
Injecting Blank Return_Reason
============================================================
Selected Rows : 4
Blank Return_Reason values injected successfully.

In [34]:
#CELL 35 - BLANK Return_Reason VALIDATION

print("=" * 60)
print("BLANK RETURN_REASON VALIDATION")
print("=" * 60)

actual_count = (
    returns_dirty.loc[selected_rows, "Return_Reason"]
    .isna()
    .sum()
)

print(f"Expected Rows : {ERROR_COUNT}")
print(f"Actual Rows   : {actual_count}")

assert actual_count == ERROR_COUNT

print("\nFirst Five Before vs After\n")

for i in range(min(5, ERROR_COUNT)):
    row = selected_rows[i]

    print(f"Row Index : {row}")

    print("Before :", repr(blank_reason_original.loc[row]))
    print("After  :", repr(returns_dirty.loc[row, "Return_Reason"]))
    print("-" * 50)

print("\nSample Modified Rows\n")

display(
    returns_dirty.loc[selected_rows]
)

print("SUCCESS: Blank Return_Reason Validation Passed")

============================================================
BLANK RETURN_REASON VALIDATION
============================================================
Expected Rows : 4
Actual Rows   : 4

First Five Before vs After

Row Index : 45
Before : 'Defective Product'
After  : nan
--------------------------------------------------
Row Index : 132
Before : 'Damaged Product'
After  : nan
--------------------------------------------------
Row Index : 30
Before : 'Changed Mind'
After  : nan
--------------------------------------------------
Row Index : 190
Before : 'Wrong Item Received'
After  : nan
--------------------------------------------------

Sample Modified Rows

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
45,R00046,O000935,C0613,P0134,2023-08-30,NaN,2240.0
132,R00133,O002641,C0202,P0056,2023-01-21,NaN,740.0
30,R00031,O000632,C0468,P0041,2023-10-09,NaN,4190.0
190,R00191,O003842,C0077,P0051,2023-05-22,NaN,5160.0

SUCCESS: Blank Return_Reason Validation Passed

In [35]:
#CELL 36 - TRACKER UPDATE

previous_count = len(modified_rows)

modified_rows.update(selected_rows)

current_count = len(modified_rows)

print("=" * 60)
print("TRACKER VALIDATION")
print("=" * 60)

print(f"Previous Count : {previous_count}")
print(f"Rows Added     : {ERROR_COUNT}")
print(f"Current Count  : {current_count}")

assert current_count == previous_count + ERROR_COUNT

print("\nSUCCESS: Modification Tracker Updated Successfully")

============================================================
TRACKER VALIDATION
============================================================
Previous Count : 61
Rows Added     : 4
Current Count  : 65

SUCCESS: Modification Tracker Updated Successfully

In [36]:
#CELL 37 - DUPLICATE RECORDS IMPLEMENTATION

print("=" * 60)
print("Injecting Duplicate Records")
print("=" * 60)

DUPLICATE_COUNT = 10

# Select rows to duplicate
duplicate_rows = random.sample(list(returns_dirty.index), DUPLICATE_COUNT)

# Store originals for validation
duplicate_records = returns_dirty.loc[
    duplicate_rows
].copy()

# Append duplicate rows
returns_dirty = pd.concat(
    [returns_dirty, duplicate_records],
    ignore_index=True
)

# Shuffle entire dataset
returns_dirty = (
    returns_dirty
    .sample(frac=1, random_state=RANDOM_SEED)
    .reset_index(drop=True)
)

print(f"Duplicate Rows Selected : {DUPLICATE_COUNT}")
print("Duplicates appended successfully.")
print("Dataset shuffled successfully.")

============================================================
Injecting Duplicate Records
============================================================
Duplicate Rows Selected : 10
Duplicates appended successfully.
Dataset shuffled successfully.

In [37]:
#CELL 38 - DUPLICATE RECORDS VALIDATION

print("=" * 60)
print("DUPLICATE RECORDS VALIDATION")
print("=" * 60)

expected_rows = len(returns_master) + DUPLICATE_COUNT
actual_rows = len(returns_dirty)

print(f"Expected Total Rows : {expected_rows}")
print(f"Actual Total Rows   : {actual_rows}")

assert actual_rows == expected_rows

duplicate_mask = returns_dirty.duplicated(keep=False)

duplicate_count = duplicate_mask.sum()

print(f"\nRows participating in duplicates : {duplicate_count}")

assert duplicate_count >= DUPLICATE_COUNT * 2

print("\nSample Duplicate Records\n")

display(
    returns_dirty.loc[duplicate_mask]
    .head(10)
)

print("SUCCESS: Duplicate Records Validation Passed")

============================================================
DUPLICATE RECORDS VALIDATION
============================================================
Expected Total Rows : 263
Actual Total Rows   : 263

Rows participating in duplicates : 20

Sample Duplicate Records

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
2,R00093,O001806,C0298,P0066,NaN,Damaged Product,1650.0
3,R00227,O004507,C0210,P0126,2025-03-22,Damaged Product,1380.0
18,R00161,O003187,C0293,P0029,2025-12-19,CHANGED MIND,47820.0
21,R00148,O002947,C0243,P0004,2024-10-28,Size/Fit Issue,3500.0
23,R00213,O004162,C0739,P0142,2025-12-14,Late Delivery,2960.0
43,R00076,O001523,C0322,P0006,2024-09-11,Wrong Item Received,50820.0
53,R00181,O003604,C0280,P0088,2025-05-05,Late Delivery,1900.0
61,R00093,O001806,C0298,P0066,NaN,Damaged Product,1650.0
71,R00050,O001040,C0291,P0131,2025-12-13,DeFeCtIvE PrOdUcT,2390.0
78,R00159,O003127,C0137,P0079,2023-10-22,Damaged Product,1970.0

SUCCESS: Duplicate Records Validation Passed

In [38]:
#CELL 39 - DUPLICATE DISTRIBUTION CHECK

print("=" * 60)
print("DUPLICATE DISTRIBUTION CHECK")
print("=" * 60)

duplicate_indices = returns_dirty.index[
    returns_dirty.duplicated(keep=False)
].tolist()

print("First 10 Duplicate Indices")

print(duplicate_indices[:10])

assert max(duplicate_indices) != len(returns_dirty) - 1

print("\nSUCCESS: Duplicate records are distributed throughout the dataset.")

============================================================
DUPLICATE DISTRIBUTION CHECK
============================================================
First 10 Duplicate Indices
[2, 3, 18, 21, 23, 43, 53, 61, 71, 78]

SUCCESS: Duplicate records are distributed throughout the dataset.

In [39]:
#CELL 40 - FINAL DATASET SHAPE VALIDATION

print("=" * 60)
print("FINAL DATASET SHAPE VALIDATION")
print("=" * 60)

expected_rows = 263
expected_columns = 7

actual_rows = returns_dirty.shape[0]
actual_columns = returns_dirty.shape[1]

print(f"Expected Rows    : {expected_rows}")
print(f"Actual Rows      : {actual_rows}")

print(f"\nExpected Columns : {expected_columns}")
print(f"Actual Columns   : {actual_columns}")

assert actual_rows == expected_rows
assert actual_columns == expected_columns

print("\nSUCCESS: Dataset shape validation passed.")

============================================================
FINAL DATASET SHAPE VALIDATION
============================================================
Expected Rows    : 263
Actual Rows      : 263

Expected Columns : 7
Actual Columns   : 7

SUCCESS: Dataset shape validation passed.

In [40]:
#CELL 41 - COLUMN STRUCTURE VALIDATION

print("=" * 60)
print("COLUMN STRUCTURE VALIDATION")
print("=" * 60)

expected_columns = [
    "Return_ID",
    "Order_ID",
    "Customer_ID",
    "Product_ID",
    "Return_Date",
    "Return_Reason",
    "Refund_Amount"
]

actual_columns = list(returns_dirty.columns)

print("Expected Columns:")
print(expected_columns)

print("\nActual Columns:")
print(actual_columns)

assert actual_columns == expected_columns

print("\nSUCCESS: Column structure validation passed.")

============================================================
COLUMN STRUCTURE VALIDATION
============================================================
Expected Columns:
['Return_ID', 'Order_ID', 'Customer_ID', 'Product_ID', 'Return_Date', 'Return_Reason', 'Refund_Amount']

Actual Columns:
['Return_ID', 'Order_ID', 'Customer_ID', 'Product_ID', 'Return_Date', 'Return_Reason', 'Refund_Amount']

SUCCESS: Column structure validation passed.

In [41]:
#CELL 42 - MASTER DATASET PROTECTION VALIDATION

print("=" * 60)
print("MASTER DATASET PROTECTION VALIDATION")
print("=" * 60)

master_rows = len(returns_master)

print(f"Master Dataset Rows : {master_rows}")

assert master_rows == 253

print("\nMaster dataset remains unchanged.")
print("SUCCESS: Master dataset protection validation passed.")

============================================================
MASTER DATASET PROTECTION VALIDATION
============================================================
Master Dataset Rows : 253

Master dataset remains unchanged.
SUCCESS: Master dataset protection validation passed.

In [42]:
#CELL 43 - MISSING VALUE AUDIT

print("=" * 60)
print("MISSING VALUE AUDIT")
print("=" * 60)

missing_summary = returns_dirty.isna().sum()

display(
    missing_summary.to_frame(
        name="Missing_Count"
    )
)

print("\nSUCCESS: Missing value audit completed.")

============================================================
MISSING VALUE AUDIT
============================================================

               Missing_Count
Return_ID                  0
Order_ID                   0
Customer_ID                0
Product_ID                 0
Return_Date                5
Return_Reason              4
Refund_Amount              4

SUCCESS: Missing value audit completed.

In [43]:
# ==========================================================
# Investigate Return_Date Missing Values
# ==========================================================

print("=" * 60)
print("RETURN_DATE MISSING VALUE INVESTIGATION")
print("=" * 60)

missing_return_dates = returns_dirty[
    returns_dirty["Return_Date"].isna()
]

print(f"Total Missing Return_Date Rows : {len(missing_return_dates)}")

display(missing_return_dates)

============================================================
RETURN_DATE MISSING VALUE INVESTIGATION
============================================================
Total Missing Return_Date Rows : 5

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
0,R00116,O002273,C0583,P0096,NaN,Late Delivery,2850.0
2,R00093,O001806,C0298,P0066,NaN,Damaged Product,1650.0
61,R00093,O001806,C0298,P0066,NaN,Damaged Product,1650.0
70,R00120,O002350,C0400,P0170,NaN,Wrong Item Received,12160.0
111,R00200,O003962,C0734,P0095,NaN,Wrong Item Received,2340.0

In [44]:
#CELL 44 - LOAD RELATED MASTER DATASETS
# ==========================================================
# Load Related Master Datasets
# ==========================================================

print("=" * 60)
print("LOADING RELATED MASTER DATASETS")
print("=" * 60)

customers_master = pd.read_csv("../01_Master_Datasets/Customer_Master.csv")
products_master = pd.read_csv("../01_Master_Datasets/Product_Master.csv")
orders_master = pd.read_csv("../01_Master_Datasets/Orders.csv")

print("Customers Loaded :", len(customers_master))
print("Products Loaded  :", len(products_master))
print("Orders Loaded    :", len(orders_master))

print("\nSUCCESS: Related datasets loaded.")

============================================================
LOADING RELATED MASTER DATASETS
============================================================
Customers Loaded : 750
Products Loaded  : 200
Orders Loaded    : 5000

SUCCESS: Related datasets loaded.

In [47]:
#CELL 45 - Order_ID RELATIONSHIP VALIDATION

print("=" * 60)
print("ORDER_ID VALIDATION")
print("=" * 60)

invalid_orders = (
    (~returns_dirty["Order_ID"].isin(orders_master["Order_ID"]))
    .sum()
)

print(f"Invalid Order_ID Count : {invalid_orders}")

assert invalid_orders == 0

print("\nSUCCESS: All Order_ID values exist in Orders table.")

============================================================
ORDER_ID VALIDATION
============================================================
Invalid Order_ID Count : 0

SUCCESS: All Order_ID values exist in Orders table.

In [49]:
#CELL 46 - Customer_ID RELATIONSHIP VALIDATION

print("=" * 60)
print("CUSTOMER_ID VALIDATION")
print("=" * 60)

invalid_customers = (
    (~returns_dirty["Customer_ID"].isin(customers_master["Customer_ID"]))
    .sum()
)

print(f"Invalid Customer_ID Count : {invalid_customers}")

assert invalid_customers == 0

print("\nSUCCESS: All Customer_ID values exist in Customer table.")

============================================================
CUSTOMER_ID VALIDATION
============================================================
Invalid Customer_ID Count : 0

SUCCESS: All Customer_ID values exist in Customer table.

In [50]:
#CELL 47 - Product_ID RELATIONSHIP VALIDATION

print("=" * 60)
print("PRODUCT_ID VALIDATION")
print("=" * 60)

invalid_products = (
    (~returns_dirty["Product_ID"].isin(products_master["Product_ID"]))
    .sum()
)

print(f"Invalid Product_ID Count : {invalid_products}")

assert invalid_products == 0

print("\nSUCCESS: All Product_ID values exist in Product table.")

============================================================
PRODUCT_ID VALIDATION
============================================================
Invalid Product_ID Count : 0

SUCCESS: All Product_ID values exist in Product table.

In [51]:
#CELL 48 - ERROR INJECTION AUDIT SUMMARY

print("=" * 70)
print("FICTIONALCART - RETURNS DIRTY DATA AUDIT SUMMARY")
print("=" * 70)

audit_summary = {
    "Error Type": [
        "Leading Spaces",
        "Trailing Spaces",
        "Double Spaces",
        "ALL CAPS",
        "Lowercase",
        "Mixed Capitalization",
        "Hidden Tabs",
        "Blank Return_Date",
        "Blank Refund_Amount",
        "Blank Return_Reason",
        "Duplicate Records"
    ],
    
    "Injected Count": [
        8,
        8,
        8,
        8,
        8,
        8,
        5,
        4,
        4,
        4,
        10
    ]
}

audit_df = pd.DataFrame(audit_summary)

display(audit_df)


print("\n" + "=" * 70)
print("DATASET SUMMARY")
print("=" * 70)

print(f"Original Rows       : {len(returns_master)}")
print(f"Final Dirty Rows    : {len(returns_dirty)}")
print(f"Rows Added          : {len(returns_dirty) - len(returns_master)}")

print("\n" + "=" * 70)
print("VALIDATION STATUS")
print("=" * 70)

print("Schema Validation              : PASSED")
print("Master Protection Validation   : PASSED")
print("Order Relationship Validation  : PASSED")
print("Customer Relationship Validation: PASSED")
print("Product Relationship Validation : PASSED")

print("\nSUCCESS: ETL Audit Summary Completed")

======================================================================
FICTIONALCART - RETURNS DIRTY DATA AUDIT SUMMARY
======================================================================

              Error Type  Injected Count
0         Leading Spaces               8
1        Trailing Spaces               8
2          Double Spaces               8
3               ALL CAPS               8
4              Lowercase               8
5   Mixed Capitalization               8
6            Hidden Tabs               5
7      Blank Return_Date               4
8    Blank Refund_Amount               4
9    Blank Return_Reason               4
10     Duplicate Records              10

======================================================================
DATASET SUMMARY
======================================================================
Original Rows       : 253
Final Dirty Rows    : 263
Rows Added          : 10

======================================================================
VALIDATION STATUS
======================================================================
Schema Validation              : PASSED
Master Protection Validation   : PASSED
Order Relationship Validation  : PASSED
Customer Relationship Validation: PASSED
Product Relationship Validation : PASSED

SUCCESS: ETL Audit Summary Completed

In [52]:
#CELL 49 - FINAL DATASET PREVIEW

print("=" * 60)
print("FINAL RETURNS_DIRTY DATASET PREVIEW")
print("=" * 60)

print("Dataset Shape:")
print(returns_dirty.shape)

print("\nFirst 10 Rows:")

display(
    returns_dirty.head(10)
)

print("\nLast 10 Rows:")

display(
    returns_dirty.tail(10)
)

print("\nSUCCESS: Final dataset preview completed.")

============================================================
FINAL RETURNS_DIRTY DATASET PREVIEW
============================================================
Dataset Shape:
(263, 7)

First 10 Rows:

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
0,R00116,O002273,C0583,P0096,NaN,Late Delivery,2850.0
1,R00121,O002360,C0586,P0087,2025-11-08,Damaged Product,44350.0
2,R00093,O001806,C0298,P0066,NaN,Damaged Product,1650.0
3,R00227,O004507,C0210,P0126,2025-03-22,Damaged Product,1380.0
4,R00067,O001409,C0087,P0100,2023-05-31,Damaged Product,2290.0
5,R00250,O004911,C0627,P0016,2025-06-14,Damaged Product,28860.0
6,R00177,O003529,C0388,P0001,2024-04-02,Wrong Item Received,35640.0
7,R00217,O004199,C0428,P0004,2024-03-08,Changed Mind,3500.0
8,R00010,O000213,C0488,P0121,2025-04-19,Changed Mind,620.0
9,R00102,O001943,C0297,P0033,2024-10-11,Changed Mind,10520.0

Last 10 Rows:

,Return_ID,Order_ID,Customer_ID,Product_ID,Return_Date,Return_Reason,Refund_Amount
253,R00075,O001517,C0423,P0106,2023-08-25,Damaged Product,13920.0
254,R00215,O004169,C0454,P0146,2024-01-05,SiZe/fIt iSsUe,1000.0
255,R00211,O004153,C0722,P0076,2025-11-08,Changed Mind,7220.0
256,R00122,O002380,C0471,P0143,2025-09-07,DAMAGED PRODUCT,550.0
257,R00181,O003604,C0280,P0088,2025-05-05,Late Delivery,1900.0
258,R00021,O000442,C0035,P0021,2024-05-29,Wrong Item Received,67780.0
259,R00189,O003817,C0262,P0169,2024-12-31,Damaged Product,11260.0
260,R00072,O001483,C0325,P0018,2024-09-12,damaged product,9650.0
261,R00107,O002045,C0220,P0128,2025-11-30,Other,2420.0
262,R00103,O001946,C0177,P0145,2025-05-12,Late Delivery,410.0

SUCCESS: Final dataset preview completed.

In [53]:
#CELL 50 - EXPORT Returns_Dirty.csv

print("=" * 60)
print("EXPORTING RETURNS_DIRTY.CSV")
print("=" * 60)

output_file = "Returns_Dirty.csv"

returns_dirty.to_csv(
    output_file,
    index=False
)

print(f"File Name : {output_file}")
print(f"Rows Exported : {len(returns_dirty)}")
print(f"Columns Exported : {len(returns_dirty.columns)}")

print("\nSUCCESS: Returns_Dirty.csv Exported Successfully")

============================================================
EXPORTING RETURNS_DIRTY.CSV
============================================================
File Name : Returns_Dirty.csv
Rows Exported : 263
Columns Exported : 7

SUCCESS: Returns_Dirty.csv Exported Successfully